language: python
sudo: false
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install pytest
- pip install -U -r requirements.txt
- pip install --no-deps -e forge
before_script:
- ./continuous_integration/travis/before-test.sh
script:
- py.test tests -s --verbose
